### ISSUE TITLE
Track per account storage usage of media

### ISSUE THREAD

**Issue by aaronc** [regen-network/regen-server#421]
For #418 and other data uploads, we want to track per account storage usage of any media and data uploads and tally it against a quota.

There are two general approaches we can take:
* keep track of the storage in some table and add/remove from the total whenever data is uploaded/deleted
* dynamically calculate the storage usage based on scanning postgres and S3 buckets

**Comment by aaronc** [comment]
My proposal is that we track sizes using database tables where the size of any S3 files are stored in a `size` column. For instance:
- an `uploads` table for S3 files
- a `posts` table for JSON-LD documents

The total storage usage would be the sum of the `size` columns for the user's content in each of these tables. It doesn't have to just be these tables, there could be 3 or 4 even if we have different content types to track.

If the query performance becomes an issue, at that point we can introduce a tracking variable or materialized view somewhere.

**Comment by blushi** [comment]
@aaronc I believe that would work, it's a flexible solution that allows for some level of granularity.

I'm also wondering if we would track the rest of the project page content that is currently stored either in the project off chain metadata as jsonb (project description, story, media urls, see our JSON-LD template: https://github.com/regen-network/regen-registry-standards/blob/main/jsonld/projects/project-page.jsonld) or in the project on chain metadata (see generic JSON-LD template: https://github.com/regen-network/regen-registry-standards/blob/main/jsonld/projects/project.jsonld).
The actual storage used for these JSON-LDs might be quite small compared to media content size, at least for the off chain metadata which is restricted to a given number of fields with a max character size for them, while we can add any number of custom fields to the on chain project metadata without further limitation atm.

With regards to JSON-LD documents, if we keep storing them as `jsonb` in the database, we could use `pg_column_size` function directly instead of having a separate `size` column for them.

**Comment by aaronc** [comment]
> I'm also wondering if we would track the rest of the project page content that is currently stored either in the project off chain metadata as jsonb (project description, story, media urls, see our JSON-LD template: https://github.com/regen-network/regen-registry-standards/blob/main/jsonld/projects/project-page.jsonld) or in the project on chain metadata (see generic JSON-LD template: https://github.com/regen-network/regen-registry-standards/blob/main/jsonld/projects/project.jsonld). The actual storage used for these JSON-LDs might be quite small compared to media content size, at least for the off chain metadata which is restricted to a given number of fields with a max character size for them, while we can add any number of custom fields to the on chain project metadata without further limitation atm.

It think it's okay to exclude these things for now but I'm thinking that eventually certain types of data files might be mapped to RDF rather than raw media. But for simplicity for now we could just focus on S3 files as JSON-LD will likely be KBs vs MBs.

> With regards to JSON-LD documents, if we keep storing them as `jsonb` in the database, we could use `pg_column_size` function directly instead of having a separate `size` column for them.

Yes, that makes sense. We don't need to separately track the size of objects stored in postgres.

**Comment by aaronc** [comment]
That sounds good. Do you think it would make sense to make the project itself the "owner" of these files? That would address what happens when a project transferred from an individual to an org. But current user is also okay for now.

**Comment by blushi** [comment]
We could also store both, project id and current account id.
